name: Daily Hello

on:
  schedule:
    - cron: "0 22 * * *" # runs every day 02:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          echo "Hello world from GitHub schedule!"
